//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDE.Resources.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDE.Resources.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Item....
        /// </summary>
        public static string CmdAddExistingItemHeader {
            get {
                return ResourceManager.GetString("CmdAddExistingItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Project....
        /// </summary>
        public static string CmdAddExistingProjectHeader {
            get {
                return ResourceManager.GetString("CmdAddExistingProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string CmdAddFolderHeader {
            get {
                return ResourceManager.GetString("CmdAddFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footprint....
        /// </summary>
        public static string CmdAddFootprintHeader {
            get {
                return ResourceManager.GetString("CmdAddFootprintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group Folder.
        /// </summary>
        public static string CmdAddGroupFolderHeader {
            get {
                return ResourceManager.GetString("CmdAddGroupFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board....
        /// </summary>
        public static string CmdAddNewBoardHeader {
            get {
                return ResourceManager.GetString("CmdAddNewBoardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component....
        /// </summary>
        public static string CmdAddNewComponentHeader {
            get {
                return ResourceManager.GetString("CmdAddNewComponentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram....
        /// </summary>
        public static string CmdAddNewDiagramHeader {
            get {
                return ResourceManager.GetString("CmdAddNewDiagramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font....
        /// </summary>
        public static string CmdAddNewFontHeader {
            get {
                return ResourceManager.GetString("CmdAddNewFontHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item....
        /// </summary>
        public static string CmdAddNewItemHeader {
            get {
                return ResourceManager.GetString("CmdAddNewItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model....
        /// </summary>
        public static string CmdAddNewModelHeader {
            get {
                return ResourceManager.GetString("CmdAddNewModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schematic....
        /// </summary>
        public static string CmdAddNewSchematicHeader {
            get {
                return ResourceManager.GetString("CmdAddNewSchematicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project....
        /// </summary>
        public static string CmdAddProjectHeader {
            get {
                return ResourceManager.GetString("CmdAddProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new sheet.
        /// </summary>
        public static string CmdAddSchematicSheetTooltip {
            get {
                return ResourceManager.GetString("CmdAddSchematicSheetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol....
        /// </summary>
        public static string CmdAddSymbolHeader {
            get {
                return ResourceManager.GetString("CmdAddSymbolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string CmdBuildHeader {
            get {
                return ResourceManager.GetString("CmdBuildHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string CmdBuildTooltip {
            get {
                return ResourceManager.GetString("CmdBuildTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CmdCompileHeader {
            get {
                return ResourceManager.GetString("CmdCompileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CmdCompileTooltip {
            get {
                return ResourceManager.GetString("CmdCompileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CmdCopyHeader {
            get {
                return ResourceManager.GetString("CmdCopyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CmdCutHeader {
            get {
                return ResourceManager.GetString("CmdCutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CmdDeleteHeader {
            get {
                return ResourceManager.GetString("CmdDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sheet.
        /// </summary>
        public static string CmdDeleteSchematicSheetTooltip {
            get {
                return ResourceManager.GetString("CmdDeleteSchematicSheetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import symbol.
        /// </summary>
        public static string CmdImportSymbolText {
            get {
                return ResourceManager.GetString("CmdImportSymbolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports primitives from an existing symbol --.
        /// </summary>
        public static string CmdImportSymbolTooltip {
            get {
                return ResourceManager.GetString("CmdImportSymbolTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage References....
        /// </summary>
        public static string CmdManageReferencesHeader {
            get {
                return ResourceManager.GetString("CmdManageReferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string CmdMoveDownTooltip {
            get {
                return ResourceManager.GetString("CmdMoveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string CmdMoveUpTooltip {
            get {
                return ResourceManager.GetString("CmdMoveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder in File Explorer.
        /// </summary>
        public static string CmdOpenContainingFolderHeader {
            get {
                return ResourceManager.GetString("CmdOpenContainingFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string CmdPasteHeader {
            get {
                return ResourceManager.GetString("CmdPasteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string CmdRenameHeader {
            get {
                return ResourceManager.GetString("CmdRenameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename sheet.
        /// </summary>
        public static string CmdRenameSchematicSheetTooltip {
            get {
                return ResourceManager.GetString("CmdRenameSchematicSheetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Manager.
        /// </summary>
        public static string CmdShowConfigurationManagerHeader {
            get {
                return ResourceManager.GetString("CmdShowConfigurationManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens configuration manager.
        /// </summary>
        public static string CmdShowConfigurationManagerTooltip {
            get {
                return ResourceManager.GetString("CmdShowConfigurationManagerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dependencies.
        /// </summary>
        public static string CmdShowProjectDependenciesHeader {
            get {
                return ResourceManager.GetString("CmdShowProjectDependenciesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string CmdShowPropertiesHeader {
            get {
                return ResourceManager.GetString("CmdShowPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        public static string CmdSolutionExplorerCollapseAllNodesTooltip {
            get {
                return ResourceManager.GetString("CmdSolutionExplorerCollapseAllNodesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CmdSolutionExplorerRefreshNodesTooltip {
            get {
                return ResourceManager.GetString("CmdSolutionExplorerRefreshNodesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update References.
        /// </summary>
        public static string CmdUpdateReferencesHeader {
            get {
                return ResourceManager.GetString("CmdUpdateReferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Fit.
        /// </summary>
        public static string CmdZoomToFitText {
            get {
                return ResourceManager.GetString("CmdZoomToFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom all content of the canvas to fit on the screen.
        /// </summary>
        public static string CmdZoomToFitTooltip {
            get {
                return ResourceManager.GetString("CmdZoomToFitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to selected.
        /// </summary>
        public static string CmdZoomToSelectedText {
            get {
                return ResourceManager.GetString("CmdZoomToSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to selected items to fit on screen.
        /// </summary>
        public static string CmdZoomToSelectedTooltip {
            get {
                return ResourceManager.GetString("CmdZoomToSelectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string CommandSaveAllText {
            get {
                return ResourceManager.GetString("CommandSaveAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string CommandSaveAllTooltip {
            get {
                return ResourceManager.GetString("CommandSaveAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommandSaveText {
            get {
                return ResourceManager.GetString("CommandSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CommandSaveTooltip {
            get {
                return ResourceManager.GetString("CommandSaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 2D.
        /// </summary>
        public static string CommandShow2DText {
            get {
                return ResourceManager.GetString("CommandShow2DText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show document in plain view.
        /// </summary>
        public static string CommandShow2DTooltip {
            get {
                return ResourceManager.GetString("CommandShow2DTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show 3D.
        /// </summary>
        public static string CommandShow3DText {
            get {
                return ResourceManager.GetString("CommandShow3DText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to clipboard.
        /// </summary>
        public static string CopyPathToClipboard {
            get {
                return ResourceManager.GetString("CopyPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAboutHeader {
            get {
                return ResourceManager.GetString("MenuAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAboutTooltip {
            get {
                return ResourceManager.GetString("MenuAboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MenuAddHeader {
            get {
                return ResourceManager.GetString("MenuAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuFileCloseHeader {
            get {
                return ResourceManager.GetString("MenuFileCloseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close solution.
        /// </summary>
        public static string MenuFileCloseSolutionHeader {
            get {
                return ResourceManager.GetString("MenuFileCloseSolutionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current solution.
        /// </summary>
        public static string MenuFileCloseSolutionTooltip {
            get {
                return ResourceManager.GetString("MenuFileCloseSolutionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current file.
        /// </summary>
        public static string MenuFileCloseTooltip {
            get {
                return ResourceManager.GetString("MenuFileCloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuFileExitHeader {
            get {
                return ResourceManager.GetString("MenuFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes application.
        /// </summary>
        public static string MenuFileExitTooltip {
            get {
                return ResourceManager.GetString("MenuFileExitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFileHeader {
            get {
                return ResourceManager.GetString("MenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelpHeader {
            get {
                return ResourceManager.GetString("MenuHelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert from EAGLE.
        /// </summary>
        public static string MenuToolsConvertFromEagleHeader {
            get {
                return ResourceManager.GetString("MenuToolsConvertFromEagleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuToolsHeader {
            get {
                return ResourceManager.GetString("MenuToolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuToolsSettingsHeader {
            get {
                return ResourceManager.GetString("MenuToolsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify settings of the application.
        /// </summary>
        public static string MenuToolsSettingsTooltip {
            get {
                return ResourceManager.GetString("MenuToolsSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuViewHeader {
            get {
                return ResourceManager.GetString("MenuViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string NewItemBrowseText {
            get {
                return ResourceManager.GetString("NewItemBrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder for solution.
        /// </summary>
        public static string NewItemCreateFolderLabel {
            get {
                return ResourceManager.GetString("NewItemCreateFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewItemDialogNewProject {
            get {
                return ResourceManager.GetString("NewItemDialogNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string NewItemLocationLabel {
            get {
                return ResourceManager.GetString("NewItemLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name:.
        /// </summary>
        public static string NewItemSolutionNameLabel {
            get {
                return ResourceManager.GetString("NewItemSolutionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in File Explorer.
        /// </summary>
        public static string OpenFolderInFileExplorer {
            get {
                return ResourceManager.GetString("OpenFolderInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string ProjectPropertiesBuildHeader {
            get {
                return ResourceManager.GetString("ProjectPropertiesBuildHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ProjectPropertiesCompanyLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProjectPropertiesDescriptionLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string ProjectPropertiesFileNameLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesFileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ProjectPropertiesGeneralHeader {
            get {
                return ResourceManager.GetString("ProjectPropertiesGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string ProjectPropertiesNamespaceLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesNamespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string ProjectPropertiesOutputFolderLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesOutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProjectPropertiesProductLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ProjectPropertiesPropertiesHeader {
            get {
                return ResourceManager.GetString("ProjectPropertiesPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectPropertiesPropertyNameColumn {
            get {
                return ResourceManager.GetString("ProjectPropertiesPropertyNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProjectPropertiesPropertyTypeColumn {
            get {
                return ResourceManager.GetString("ProjectPropertiesPropertyTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ProjectPropertiesPropertyValueColumn {
            get {
                return ResourceManager.GetString("ProjectPropertiesPropertyValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ProjectPropertiesTitleLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ProjectPropertiesVersionLabel {
            get {
                return ResourceManager.GetString("ProjectPropertiesVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string SchematicPropertiesBomHeader {
            get {
                return ResourceManager.GetString("SchematicPropertiesBomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Classes.
        /// </summary>
        public static string SchematicPropertiesNetClassesHeader {
            get {
                return ResourceManager.GetString("SchematicPropertiesNetClassesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current theme.
        /// </summary>
        public static string SeetingsEnvGeneralCurrentThemeLabel {
            get {
                return ResourceManager.GetString("SeetingsEnvGeneralCurrentThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SetingsEnvGeneralLanguageLabel {
            get {
                return ResourceManager.GetString("SetingsEnvGeneralLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas background color.
        /// </summary>
        public static string SettingsBoardCanvasBackColorLabel {
            get {
                return ResourceManager.GetString("SettingsBoardCanvasBackColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid color.
        /// </summary>
        public static string SettingsBoardGridColorLabel {
            get {
                return ResourceManager.GetString("SettingsBoardGridColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore obstacles.
        /// </summary>
        public static string SettingsBoardIgnoreObstaclesLabel {
            get {
                return ResourceManager.GetString("SettingsBoardIgnoreObstaclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile board on document change.
        /// </summary>
        public static string SettingsBoardOnlineDRCLabel {
            get {
                return ResourceManager.GetString("SettingsBoardOnlineDRCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push obstacles.
        /// </summary>
        public static string SettingsBoardPushObstaclesLabel {
            get {
                return ResourceManager.GetString("SettingsBoardPushObstaclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repour polygons on document change.
        /// </summary>
        public static string SettingsBoardRepourPolysOnDocumentChangeLabel {
            get {
                return ResourceManager.GetString("SettingsBoardRepourPolysOnDocumentChangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unconnected signals.
        /// </summary>
        public static string SettingsBoardShowUnconnectedSignalsLabel {
            get {
                return ResourceManager.GetString("SettingsBoardShowUnconnectedSignalsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop at first obstacle.
        /// </summary>
        public static string SettingsBoardStopAtFirstObstacleLabel {
            get {
                return ResourceManager.GetString("SettingsBoardStopAtFirstObstacleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkaround obstacles.
        /// </summary>
        public static string SettingsBoardWalkAroundObstaclesLabel {
            get {
                return ResourceManager.GetString("SettingsBoardWalkAroundObstaclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto detect file changes outside environment.
        /// </summary>
        public static string SettingsEnvGeneralAutoDetectFileIsChangedLabel {
            get {
                return ResourceManager.GetString("SettingsEnvGeneralAutoDetectFileIsChangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto reload files.
        /// </summary>
        public static string SettingsEnvGeneralAutoReloadFilesLabel {
            get {
                return ResourceManager.GetString("SettingsEnvGeneralAutoReloadFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string SettingsEnvGeneralCheckForUpdatesLabel {
            get {
                return ResourceManager.GetString("SettingsEnvGeneralCheckForUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number items visible recent.
        /// </summary>
        public static string SettingsEnvGeneralNumberItemsVisibleInMRULabel {
            get {
                return ResourceManager.GetString("SettingsEnvGeneralNumberItemsVisibleInMRULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items visible in window menu.
        /// </summary>
        public static string SettingsEnvGeneralNumberItemsVisibleInWindowMenuLabel {
            get {
                return ResourceManager.GetString("SettingsEnvGeneralNumberItemsVisibleInWindowMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas background color.
        /// </summary>
        public static string SettingsSchematicCanvasBackColorLabel {
            get {
                return ResourceManager.GetString("SettingsSchematicCanvasBackColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid color.
        /// </summary>
        public static string SettingsSchematicGridColorLabel {
            get {
                return ResourceManager.GetString("SettingsSchematicGridColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads page.
        /// </summary>
        public static string StartPageDownloadsPageText {
            get {
                return ResourceManager.GetString("StartPageDownloadsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string StartPageGithubLabel {
            get {
                return ResourceManager.GetString("StartPageGithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project ....
        /// </summary>
        public static string StartPageNewProject {
            get {
                return ResourceManager.GetString("StartPageNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project from samples ....
        /// </summary>
        public static string StartPageNewProjectFromSamples {
            get {
                return ResourceManager.GetString("StartPageNewProjectFromSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online tutorials.
        /// </summary>
        public static string StartPageOnlineTutorialsLabel {
            get {
                return ResourceManager.GetString("StartPageOnlineTutorialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project ....
        /// </summary>
        public static string StartPageOpenProject {
            get {
                return ResourceManager.GetString("StartPageOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string StartPageRecentLabel {
            get {
                return ResourceManager.GetString("StartPageRecentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string StartPageRepositoriesText {
            get {
                return ResourceManager.GetString("StartPageRepositoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartPageStartLabel {
            get {
                return ResourceManager.GetString("StartPageStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string StartPageUpdatesLabel {
            get {
                return ResourceManager.GetString("StartPageUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video tutorials.
        /// </summary>
        public static string StartPageVideoTutorialsLabel {
            get {
                return ResourceManager.GetString("StartPageVideoTutorialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string StartPageWebsiteText {
            get {
                return ResourceManager.GetString("StartPageWebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Channel.
        /// </summary>
        public static string StartPageYoutubeChannelText {
            get {
                return ResourceManager.GetString("StartPageYoutubeChannelText", resourceCulture);
            }
        }
    }
}
