//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDE.Core.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoardDesignerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardDesignerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDE.Core.Presentation.Resources.BoardDesignerStrings", typeof(BoardDesignerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Electrical Clearance rule.
        /// </summary>
        public static string AddElectricalClearanceRuleTooltip {
            get {
                return ResourceManager.GetString("AddElectricalClearanceRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string AddGroupRuleTooltip {
            get {
                return ResourceManager.GetString("AddGroupRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hole size rule.
        /// </summary>
        public static string AddHoleSizeRuleTooltip {
            get {
                return ResourceManager.GetString("AddHoleSizeRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manufacturing clearance rule.
        /// </summary>
        public static string AddManufacturingClearanceRuleTooltip {
            get {
                return ResourceManager.GetString("AddManufacturingClearanceRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mask Expansion rule.
        /// </summary>
        public static string AddMaskExpansionRuleTooltip {
            get {
                return ResourceManager.GetString("AddMaskExpansionRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new dielectric layer.
        /// </summary>
        public static string AddNewDielectricLayerTooltip {
            get {
                return ResourceManager.GetString("AddNewDielectricLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new drill pair.
        /// </summary>
        public static string AddNewDrillPairTooltip {
            get {
                return ResourceManager.GetString("AddNewDrillPairTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new generic layer.
        /// </summary>
        public static string AddNewGenericLayerTooltip {
            get {
                return ResourceManager.GetString("AddNewGenericLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new layer group.
        /// </summary>
        public static string AddNewLayerGroupTooltip {
            get {
                return ResourceManager.GetString("AddNewLayerGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new layer pair.
        /// </summary>
        public static string AddNewLayerPairTooltip {
            get {
                return ResourceManager.GetString("AddNewLayerPairTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new mechanical layer.
        /// </summary>
        public static string AddNewMechanicalLayerTooltip {
            get {
                return ResourceManager.GetString("AddNewMechanicalLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new plane layer.
        /// </summary>
        public static string AddNewPlaneLayerTooltip {
            get {
                return ResourceManager.GetString("AddNewPlaneLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new signal layer.
        /// </summary>
        public static string AddNewSignalLayerTooltip {
            get {
                return ResourceManager.GetString("AddNewSignalLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track Width rule.
        /// </summary>
        public static string AddTrackWidthRuleTooltip {
            get {
                return ResourceManager.GetString("AddTrackWidthRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Via definition rule.
        /// </summary>
        public static string AddViaDefinitionRuleTooltip {
            get {
                return ResourceManager.GetString("AddViaDefinitionRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies for.
        /// </summary>
        public static string AppliesForLabel {
            get {
                return ResourceManager.GetString("AppliesForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly drawings.
        /// </summary>
        public static string AssemblyDrawingsText {
            get {
                return ResourceManager.GetString("AssemblyDrawingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string AssemblyTabHeader {
            get {
                return ResourceManager.GetString("AssemblyTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned layers.
        /// </summary>
        public static string AssignedLayersLabel {
            get {
                return ResourceManager.GetString("AssignedLayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available layers.
        /// </summary>
        public static string AvailableLayersLabel {
            get {
                return ResourceManager.GetString("AvailableLayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string BOMTabHeader {
            get {
                return ResourceManager.GetString("BOMTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Layer.
        /// </summary>
        public static string BottomLayerColumnHeader {
            get {
                return ResourceManager.GetString("BottomLayerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance.
        /// </summary>
        public static string ClearanceLabel {
            get {
                return ResourceManager.GetString("ClearanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string ColumnNameColumnHeader {
            get {
                return ResourceManager.GetString("ColumnNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string ColumnsText {
            get {
                return ResourceManager.GetString("ColumnsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create zip file for board.
        /// </summary>
        public static string CreateZipFileForBoard {
            get {
                return ResourceManager.GetString("CreateZipFileForBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current schematic.
        /// </summary>
        public static string CurrentSchematicText {
            get {
                return ResourceManager.GetString("CurrentSchematicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string DiameterLabel {
            get {
                return ResourceManager.GetString("DiameterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Pairs.
        /// </summary>
        public static string DrillPairsLabel {
            get {
                return ResourceManager.GetString("DrillPairsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill pairs.
        /// </summary>
        public static string DrillPairsTabHeader {
            get {
                return ResourceManager.GetString("DrillPairsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Clearance.
        /// </summary>
        public static string ECRuleTitle {
            get {
                return ResourceManager.GetString("ECRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion.
        /// </summary>
        public static string ExpansionLabel {
            get {
                return ResourceManager.GetString("ExpansionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export layers ....
        /// </summary>
        public static string ExportLayersTooltip {
            get {
                return ResourceManager.GetString("ExportLayersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export rules ....
        /// </summary>
        public static string ExportRulesTooltip {
            get {
                return ResourceManager.GetString("ExportRulesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string FileExtensionColumnHeader {
            get {
                return ResourceManager.GetString("FileExtensionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTabHeader {
            get {
                return ResourceManager.GetString("GeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerber File Name.
        /// </summary>
        public static string GerberFileNameColumnHeader {
            get {
                return ResourceManager.GetString("GerberFileNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerber Files.
        /// </summary>
        public static string GerberFilesLabel {
            get {
                return ResourceManager.GetString("GerberFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        public static string GroupByLabel {
            get {
                return ResourceManager.GetString("GroupByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupRuleTitle {
            get {
                return ResourceManager.GetString("GroupRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string HeaderColumnHeader {
            get {
                return ResourceManager.GetString("HeaderColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole.
        /// </summary>
        public static string HoleLabel {
            get {
                return ResourceManager.GetString("HoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import layers ....
        /// </summary>
        public static string ImportLayersTooltip {
            get {
                return ResourceManager.GetString("ImportLayersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import rules ....
        /// </summary>
        public static string ImportRulesTooltip {
            get {
                return ResourceManager.GetString("ImportRulesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Color.
        /// </summary>
        public static string LayerColorColumnHeader {
            get {
                return ResourceManager.GetString("LayerColorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Groups.
        /// </summary>
        public static string LayerGroupsLabel {
            get {
                return ResourceManager.GetString("LayerGroupsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer groups.
        /// </summary>
        public static string LayerGroupsTabHeader {
            get {
                return ResourceManager.GetString("LayerGroupsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string LayerMaterialColumnHeader {
            get {
                return ResourceManager.GetString("LayerMaterialColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Name.
        /// </summary>
        public static string LayerNameColumnHeader {
            get {
                return ResourceManager.GetString("LayerNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Pairs.
        /// </summary>
        public static string LayerPairsLabel {
            get {
                return ResourceManager.GetString("LayerPairsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer pairs.
        /// </summary>
        public static string LayerPairsTabHeader {
            get {
                return ResourceManager.GetString("LayerPairsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string LayersTabHeader {
            get {
                return ResourceManager.GetString("LayersTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose to display either all layers or the stack up for this board.
        /// </summary>
        public static string LayerStackupSpecTooltip {
            get {
                return ResourceManager.GetString("LayerStackupSpecTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string LayersText {
            get {
                return ResourceManager.GetString("LayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness (mm).
        /// </summary>
        public static string LayerThicknessColumnHeader {
            get {
                return ResourceManager.GetString("LayerThicknessColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Type.
        /// </summary>
        public static string LayerTypeColumnHeader {
            get {
                return ResourceManager.GetString("LayerTypeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingStatusText {
            get {
                return ResourceManager.GetString("LoadingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing clearance.
        /// </summary>
        public static string ManufacturingClearanceRuleTitle {
            get {
                return ResourceManager.GetString("ManufacturingClearanceRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole size.
        /// </summary>
        public static string ManufacturingHoleSizeRuleTitle {
            get {
                return ResourceManager.GetString("ManufacturingHoleSizeRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string ManufacturingTabHeader {
            get {
                return ResourceManager.GetString("ManufacturingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask expansion.
        /// </summary>
        public static string MaskExpansionRuleTitle {
            get {
                return ResourceManager.GetString("MaskExpansionRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string MirrorColumnHeader {
            get {
                return ResourceManager.GetString("MirrorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDownTooltip {
            get {
                return ResourceManager.GetString("MoveDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUpTooltip {
            get {
                return ResourceManager.GetString("MoveUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC Drill Files.
        /// </summary>
        public static string NCDrillFilesTitle {
            get {
                return ResourceManager.GetString("NCDrillFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This board doesn&apos;t have a referenced schematic.
        /// </summary>
        public static string NoSchematicReferenceLabelText {
            get {
                return ResourceManager.GetString("NoSchematicReferenceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string NotSetText {
            get {
                return ResourceManager.GetString("NotSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputTabHeader {
            get {
                return ResourceManager.GetString("OutputTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick and place files.
        /// </summary>
        public static string PickAndPlaceFilesText {
            get {
                return ResourceManager.GetString("PickAndPlaceFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string PlotColumnHeader {
            get {
                return ResourceManager.GetString("PlotColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot board outline on all layers.
        /// </summary>
        public static string PlotOutlineOnAllLayers {
            get {
                return ResourceManager.GetString("PlotOutlineOnAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display copper as layer colors.
        /// </summary>
        public static string Preview3DDisplayCopperAsLayerColors {
            get {
                return ResourceManager.GetString("Preview3DDisplayCopperAsLayerColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dielectric.
        /// </summary>
        public static string Preview3DShowDielectric {
            get {
                return ResourceManager.GetString("Preview3DShowDielectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show parts.
        /// </summary>
        public static string Preview3DShowParts {
            get {
                return ResourceManager.GetString("Preview3DShowParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PCB.
        /// </summary>
        public static string Preview3DShowPcb {
            get {
                return ResourceManager.GetString("Preview3DShowPcb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show solder mask.
        /// </summary>
        public static string Preview3DShowSolderMask {
            get {
                return ResourceManager.GetString("Preview3DShowSolderMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silkscreen color.
        /// </summary>
        public static string Preview3DSilkscreenColor {
            get {
                return ResourceManager.GetString("Preview3DSilkscreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder mask color.
        /// </summary>
        public static string Preview3DSolderMaskColor {
            get {
                return ResourceManager.GetString("Preview3DSolderMaskColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected layer group.
        /// </summary>
        public static string RemoveLayerGroupTooltip {
            get {
                return ResourceManager.GetString("RemoveLayerGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected node.
        /// </summary>
        public static string RemoveRuleTooltip {
            get {
                return ResourceManager.GetString("RemoveRuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string RuleCommentLabel {
            get {
                return ResourceManager.GetString("RuleCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string RuleDefaultValueLabel {
            get {
                return ResourceManager.GetString("RuleDefaultValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string RuleEnabledLabel {
            get {
                return ResourceManager.GetString("RuleEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by drill pair.
        /// </summary>
        public static string RuleFilterByDrillPair {
            get {
                return ResourceManager.GetString("RuleFilterByDrillPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string RuleFilterByLabel {
            get {
                return ResourceManager.GetString("RuleFilterByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter first object by.
        /// </summary>
        public static string RuleFilterFirstObjectLabel {
            get {
                return ResourceManager.GetString("RuleFilterFirstObjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter second object by.
        /// </summary>
        public static string RuleFilterSecondObjectLabel {
            get {
                return ResourceManager.GetString("RuleFilterSecondObjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string RuleLayerNameHeader {
            get {
                return ResourceManager.GetString("RuleLayerNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string RuleMaxValueLabel {
            get {
                return ResourceManager.GetString("RuleMaxValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string RuleMinValueLabel {
            get {
                return ResourceManager.GetString("RuleMinValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RuleNameLabel {
            get {
                return ResourceManager.GetString("RuleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string RulesTabHeader {
            get {
                return ResourceManager.GetString("RulesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set schematic reference.
        /// </summary>
        public static string SetSchematicReferenceButtonText {
            get {
                return ResourceManager.GetString("SetSchematicReferenceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show board.
        /// </summary>
        public static string ShowBoardButtonText {
            get {
                return ResourceManager.GetString("ShowBoardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowColumnHeader {
            get {
                return ResourceManager.GetString("ShowColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stackup.
        /// </summary>
        public static string StackupTabHeader {
            get {
                return ResourceManager.GetString("StackupTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Layer.
        /// </summary>
        public static string StartLayerColumnHeader {
            get {
                return ResourceManager.GetString("StartLayerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Layer.
        /// </summary>
        public static string StopLayerColumnHeader {
            get {
                return ResourceManager.GetString("StopLayerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are changes detected in schematic.
        /// </summary>
        public static string ThereAreDetectedSchematicChangesLabelText {
            get {
                return ResourceManager.GetString("ThereAreDetectedSchematicChangesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Layer.
        /// </summary>
        public static string TopLayerColumnHeader {
            get {
                return ResourceManager.GetString("TopLayerColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total thickness:.
        /// </summary>
        public static string TotalBoardThicknessLabel {
            get {
                return ResourceManager.GetString("TotalBoardThicknessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track width.
        /// </summary>
        public static string TrackWidthRuleTitle {
            get {
                return ResourceManager.GetString("TrackWidthRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update board from schematic.
        /// </summary>
        public static string UpdateBoardFromSchematicButtonText {
            get {
                return ResourceManager.GetString("UpdateBoardFromSchematicButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via definition.
        /// </summary>
        public static string ViaDefinitionRuleTitle {
            get {
                return ResourceManager.GetString("ViaDefinitionRuleTitle", resourceCulture);
            }
        }
    }
}
