//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDE.Core.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchematicStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchematicStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDE.Core.Presentation.Resources.SchematicStrings", typeof(SchematicStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new net class.
        /// </summary>
        public static string AddClassCommandTooltip {
            get {
                return ResourceManager.GetString("AddClassCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string AddGroupCommandTooltip {
            get {
                return ResourceManager.GetString("AddGroupCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned nets.
        /// </summary>
        public static string AssignedNets {
            get {
                return ResourceManager.GetString("AssignedNets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available nets.
        /// </summary>
        public static string AvailableNets {
            get {
                return ResourceManager.GetString("AvailableNets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        public static string BomTabHeader {
            get {
                return ResourceManager.GetString("BomTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document height (mm).
        /// </summary>
        public static string DocumentHeight {
            get {
                return ResourceManager.GetString("DocumentHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document sizes.
        /// </summary>
        public static string DocumentSizes {
            get {
                return ResourceManager.GetString("DocumentSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document width (mm).
        /// </summary>
        public static string DocumentWidth {
            get {
                return ResourceManager.GetString("DocumentWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical rules (ERC).
        /// </summary>
        public static string ERCTabHeader {
            get {
                return ResourceManager.GetString("ERCTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTabHeader {
            get {
                return ResourceManager.GetString("GeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net classes.
        /// </summary>
        public static string NetClasses {
            get {
                return ResourceManager.GetString("NetClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Classes.
        /// </summary>
        public static string NetClassesTabHeader {
            get {
                return ResourceManager.GetString("NetClassesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiZ.
        /// </summary>
        public static string PinTypeHiZ {
            get {
                return ResourceManager.GetString("PinTypeHiZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string PinTypeInput {
            get {
                return ResourceManager.GetString("PinTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        public static string PinTypeIO {
            get {
                return ResourceManager.GetString("PinTypeIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoConnect.
        /// </summary>
        public static string PinTypeNoConnect {
            get {
                return ResourceManager.GetString("PinTypeNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCollector.
        /// </summary>
        public static string PinTypeOpenCollector {
            get {
                return ResourceManager.GetString("PinTypeOpenCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenEmitter.
        /// </summary>
        public static string PinTypeOpenEmitter {
            get {
                return ResourceManager.GetString("PinTypeOpenEmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string PinTypeOutput {
            get {
                return ResourceManager.GetString("PinTypeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        public static string PinTypePassive {
            get {
                return ResourceManager.GetString("PinTypePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string PinTypePower {
            get {
                return ResourceManager.GetString("PinTypePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected node.
        /// </summary>
        public static string RemoveClassNodeCommandTooltip {
            get {
                return ResourceManager.GetString("RemoveClassNodeCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show schematic.
        /// </summary>
        public static string ShowSchematic {
            get {
                return ResourceManager.GetString("ShowSchematic", resourceCulture);
            }
        }
    }
}
